XDG_RUNTIME_DIR=/run/user/%GM_RDP_USER%
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/%GM_RDP_USER%/bus
WAYLAND_DISPLAY=wayland-0
DISPLAY=:0
XDG_CURRENT_DESKTOP=GNOME
XDG_SESSION_TYPE=wayland
XDG_SESSION_DESKTOP=gnome
XDG_MENU_PREFIX=gnome-
DESKTOP_SESSION=gnome
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
GNOME_SHELL_SESSION_MODE=user

LIBGL_ALWAYS_SOFTWARE=1
MESA_GL_VERSION_OVERRIDE=4.5