[Unit]
After=org.gnome.Shell@user.service gnome-session.service gnome-settings-daemon.target gnome-bootstrap-rdp.service
Requires=org.gnome.Shell@user.service gnome-bootstrap-rdp.service
Wants=graphical-session.target

[Service]
Restart=always
RestartSec=2
