[Unit]
Description=GnomeSurface Shell (overriding GNOME Shell)
After=gnome-session.service
Requires=gnome-session.service

[Service]
Type=notify
NotifyAccess=all
Environment=XDG_SESSION_TYPE=wayland
Environment=XDG_SESSION_CLASS=user
Environment=XDG_CURRENT_DESKTOP=GNOME
Environment=XDG_DESKTOP_SESSION=gnome
Environment=DESKTOP_SESSION=gnome
ExecStart=
ExecStart=/usr/bin/dotnet gnomesurfaceshell shell:mode=%i
